version: '3.8'

services:
  spark-master:
    container_name: spark-master
    build: .
    image: vinukarthek/apache-spark:latest
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./book_data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - '9090:8080'
      - '7077:7077'

  spark-worker:
    container_name: spark-worker
    image: vinukarthek/apache-spark:latest
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-master
    environment:
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - ./book_data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events

  spark-history-server:
    container_name: spark-history
    image: vinukarthek/apache-spark:latest
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-master
    environment:
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - spark-logs:/opt/spark/spark-events
    ports:
      - '18080:18080'

volumes:
  spark-logs: